### ISSUE TITLE
User stories - Administrator - Sign up feature

### ISSUE THREAD

**Issue by Christoph33one** [Christoph33one/my-first-project#1]
# User story:
As the **sites administrator** I need to **include a sign up form** and **conformation** to be sent to the **user**

# Acceptance Criteria: 
- The user to easy view the sign up button ( navigation bar ).
- A simple form layout for the user to understand.
- A submit button within the form.
- The user to receive a confirmation email from the site( site security ).
- The user to find a sign in function on all pages ( navigation bar ).

## Tasks:
- [ ] Update the view: Create a sign up button and links ( HTML and CSS) in the Navigation menu.
- [ ] Add a new page to the site for sign up only.
- [ ] Design a form: Add a clear layout and instructions for the user to enter details.
- [ ] Secure site conformation: User to receive an email (using the mailto method) confirming they have an account.
- [ ] Include a sign in function ( HTML and CSS ).
- [ ] Test all functions work and are compatible to different web browsers.
