### ISSUE TITLE
User stories - User - sign up feature.

### ISSUE THREAD

**Issue by Christoph33one** [Christoph33one/my-first-project#2]
# Acceptance Criteria :

As a **user of the website** I want the ability to **sign up** to the website by,

* The option to see a sign up link.
* The link to send me to a secure signup application.
* A clear application form to add my details .
* A conformation email, that I have an account.
* An option to sign in.

## Tasks: 

- [ ] Update the view: A sign up button and links ( HTML and CSS) in the Navigation menu.
- [ ] A new page to the site for sign up only.
- [ ] Form design: A clear layout and instructions to enter details.
- [ ] Secure site conformation: To receive an email confirming stating I have an account.
- [ ] Update the view: A clear sign in function. 
- [ ] Test functionality.
